FROM flink:1.19-scala_2.12-java8

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    python -m pip install --upgrade pip 


RUN pip install apache-flink==1.19.0

# COPY ./lib-flink /opt/flink/lib/



WORKDIR /opt/flink