FROM apache/airflow:2.7.1-python3.8

USER root

RUN apt-get update \
    && apt-get install -y openjdk-11-jdk \
    && apt-get clean 

# Set JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

USER airflow

RUN pip install \
    apache-airflow-providers-apache-spark==4.0.1 \
    pyspark==3.5.1 \
    clickhouse-driver \
    pandas\
    pyarrow \
    python-dotenv